# Generated by Django 3.1.1 on 2025-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
