# Generated by Django 5.2.1 on 2025-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
