# Generated by Django 3.2 on 2025-05-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_lesson_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcript_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
