# Generated by Django 3.1.1 on 2025-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_lesson_transcript_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
