# Generated by Django 3.1.1 on 2025-06-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_lesson_pdf_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_text',
        ),
    ]
